
name: turtleFSI
channels:
  - conda-forge
dependencies:
  - fenics-dolfin
  - metis=5.1.0
  - hdf5=1.12.2
  - mpi4py=3.1.4
  - python>3.7
  - pip
  - git
  - scipy
  - configargparse
  - numpy
  - pyyaml