name: Test against FEniCS master branch

on:
  push:
    # The CI is executed on every push on every branch
    branches:
      - master
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - master

  schedule:
    # The CI is executed every day at 8am
    - cron: "0 8 * * *"
jobs:
  test-code:
    runs-on: ubuntu-22.04
    # Runs against FEniCS main branch
    container: ghcr.io/scientificcomputing/fenics:2023-04-21
    steps:
      # This action sets the current path to the root of your github repo
      - uses: actions/checkout@v3
      

      - name: "Install code"
        run: python3 setup.py install
      - name: Run tests
        run: |
          python3 -m pytest